PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE GENERALINFORMATION(NO INTEGER, TITLE VARCHAR(1000),     BANNERCONTENT1 VARCHAR(1000), BANNERCONTENT2 VARCHAR(1000));
CREATE TABLE ABOUTCONTENT(NO INTEGER, CONTENT VARCHAR(10000), DETAILS DATE);
CREATE TABLE ABOUTCONTACT(NO INTEGER,CONTACTBRIEF VARCHAR(10000), CONTACTADD1 VARCHAR(10000), CONTACTADD2 VARCHAR(10000),          CONTACTMAIL VARCHAR(1000), CONTACTPHONE VARCHAR(1000),DETAILS DATETIME);
CREATE TABLE ABOUTTEAM(NO INTEGER, TEAMBRIEF VARCHAR(10000), DETAILS DATETIME);
CREATE TABLE TEAMMEMBERS(NO INTEGER, NAME VARCHAR(1000), POSITION VARCHAR(1000), BRIEF VARCHAR(1000), DETAILS DATETIME);
CREATE TABLE ABOUTFOOTER(NO INTEGER, FOOTERCONTENT VARCHAR(10000), DETAILS DATETIME);
COMMIT;
